apiVersion: v1
kind: Namespace
metadata:
  name: order-intake-pov
  labels:
    app.kubernetes.io/name: order-intake
    app.kubernetes.io/part-of: hybrid-cloud-modernization-pov
    purpose: proof-of-value
