apiVersion: v1
kind: Service
metadata:
  name: order-intake
  namespace: order-intake-pov
  labels:
    app.kubernetes.io/name: order-intake
spec:
  selector:
    app.kubernetes.io/name: order-intake
  ports:
    - name: http
      port: 8080
      targetPort: http
